import React, { useState } from 'react';
import { 
  Users, 
  Bed, 
  Stethoscope, 
  Activity, 
  AlertTriangle, 
  Sparkles, 
  ArrowRight, 
  Clock, 
  CheckCircle2, 
  TrendingUp,
  Info,
  ChevronRight,
  Download,
  AlertOctagon,
  ArrowUpRight,
  ArrowDownRight,
  ShieldAlert,
  Flame,
  X,
  FileSpreadsheet
} from 'lucide-react';
import { HospitalMetrics, OperationalAlert, BedAllocation, StaffOnDuty, Patient, MediFlowView, HospitalUserRole } from '../types';
import { DAILY_CHANGES } from '../lib/mockHospitalData';
import { KPIGrid } from './dashboard/KPIGrid';
import { AttentionPanel } from './dashboard/AttentionPanel';
import { CapacityOverview } from './dashboard/CapacityOverview';
import { PatientFlow } from './patient/PatientFlow';

interface HospitalOperationsDashboardProps {
  metrics: HospitalMetrics;
  alerts: OperationalAlert[];
  beds: BedAllocation[];
  staff: StaffOnDuty[];
  patients: Patient[];
  activeRole?: HospitalUserRole;
  onNavigate: (view: MediFlowView) => void;
  onReviewRecommendation: () => void;
}

export const HospitalOperationsDashboard: React.FC<HospitalOperationsDashboardProps> = ({
  metrics,
  alerts,
  beds,
  staff,
  patients,
  activeRole = 'administrator',
  onNavigate,
  onReviewRecommendation
}) => {
  const [briefExported, setBriefExported] = useState(false);
  const [dailyChangesModalOpen, setDailyChangesModalOpen] = useState(false);

  const handleExportBrief = () => {
    const briefText = `MEDIFLOW MORNING OPERATIONAL BRIEF - 09:00 AM\n\n` +
      `• Hospital capacity is currently at 81% overall; ICU occupancy is 87%.\n` +
      `• ICU occupancy has increased by +8% since yesterday.\n` +
      `• 12 patients are currently classified as critical; 3 awaiting ICU placement.\n` +
      `• Emergency waiting time is 42m (above the department's configured 30m threshold).\n` +
      `• 6 additional ICU beds projected to be required over the next 6 hours.\n\n` +
      `Generated by MediFlow Hospital Command Center at ${new Date().toLocaleString()}`;
    
    const blob = new Blob([briefText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mediflow-morning-brief-${new Date().toISOString().slice(0,10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setBriefExported(true);
    setTimeout(() => setBriefExported(false), 3000);
  };

  return (
    <div className="p-6 sm:p-8 max-w-7xl mx-auto space-y-6 text-slate-100">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-[#1F3729]">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl sm:text-3xl font-serif font-bold tracking-tight text-white flex items-center gap-3">
              <span>Hospital Operations Center</span>
            </h1>
            <span className="text-[11px] font-mono px-3 py-1 rounded-full bg-[#183124] text-emerald-400 border border-[#234230] uppercase font-bold tracking-wider">
              {activeRole.replace('_', ' ')}
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-400 mt-1 font-light">
            Real-time telemetry, 3D capacity spatial tracking, predictive risk & clinical workflows
          </p>
        </div>

        <div className="flex items-center gap-3 self-start sm:self-auto">
          <div className="text-xs text-slate-400 font-mono bg-[#13251B] px-3 py-1.5 rounded-xl border border-[#234230]">
            Last updated: <span className="font-semibold text-emerald-300">{metrics.lastUpdated}</span>
          </div>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-emerald-950/80 text-emerald-300 text-xs font-semibold border border-emerald-700/60 shadow-xs">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
            <span className="font-mono uppercase tracking-wider text-[11px]">Live Telemetry</span>
          </div>
        </div>
      </div>

      {/* Morning Operational Brief (Backlog Item #8) */}
      <div className="bg-gradient-to-r from-[#14281E] via-[#162D21] to-[#14281E] rounded-2xl p-6 border border-[#274633] shadow-xl relative overflow-hidden group">
        <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2 max-w-3xl">
            <div className="flex items-center gap-2.5">
              <span className="w-2.5 h-2.5 rounded-full bg-amber-400 animate-ping" />
              <span className="w-2.5 h-2.5 rounded-full bg-amber-400 -ml-4" />
              <h3 className="text-xs font-bold uppercase tracking-widest text-amber-300 font-mono">
                Morning Operational Brief — 09:00 AM
              </h3>
            </div>
            <p className="text-base sm:text-lg font-semibold text-white leading-snug">
              Hospital capacity is currently <span className="text-amber-300 font-mono">81%</span>. ICU occupancy has increased by <span className="text-rose-400 font-mono">+8%</span> since yesterday with <span className="text-white font-mono">12</span> critical patients triaged.
            </p>
            <p className="text-xs text-slate-300 leading-relaxed font-light">
              Emergency wait times exceed the 30-min departmental threshold (current: 42 min). Surge model projects 6 additional ICU beds will be required by 15:00 if current intake velocity continues.
            </p>
          </div>

          <div className="flex items-center flex-wrap gap-2.5 shrink-0">
            <button
              onClick={() => onNavigate('patients')}
              className="px-4 py-2 rounded-xl bg-[#1C3326] hover:bg-[#234230] text-slate-200 font-semibold text-xs border border-[#2F523C] transition-all hover:scale-102 flex items-center gap-1.5"
            >
              <span>Review Issues</span>
              <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
            </button>
            <button
              onClick={() => onNavigate('insights')}
              className="px-4 py-2 rounded-xl bg-[#1C3326] hover:bg-[#234230] text-slate-200 font-semibold text-xs border border-[#2F523C] transition-all hover:scale-102 flex items-center gap-1.5"
            >
              <Sparkles className="w-3.5 h-3.5 text-amber-300" />
              <span>View Forecast</span>
            </button>
            <button
              onClick={handleExportBrief}
              className="px-4 py-2 rounded-xl bg-[#E88F89] hover:bg-[#F2A39F] text-slate-950 font-bold text-xs transition-all shadow-md shadow-[#E88F89]/20 flex items-center gap-1.5 active:scale-95"
            >
              <Download className="w-3.5 h-3.5" />
              <span>{briefExported ? 'Brief Exported' : 'Export Brief'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Interactive KPI Cards (Requirement 6) */}
      <KPIGrid metrics={metrics} onNavigate={onNavigate} />

      {/* 3D Hospital Capacity Spatial Visualization (Requirement 1) */}
      <CapacityOverview
        beds={beds}
        staff={staff}
        onNavigate={onNavigate}
        onSelectWard={(ward) => onNavigate('beds')}
      />

      {/* Dynamic Patient-Resource Flow Visualization (Requirement 3) */}
      <PatientFlow
        patients={patients}
        beds={beds}
        staff={staff}
        onNavigate={onNavigate}
      />

      {/* "What Needs Attention?" Bottlenecks (Requirement 10 / Backlog Item 9) */}
      <AttentionPanel onNavigate={onNavigate} />

      {/* Primary Surge Protocol Trigger & Quick Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Surge Protocol Quick Trigger */}
        <div className="lg:col-span-2 bg-[#13251B] rounded-2xl p-6 border border-[#234230] shadow-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-amber-400" />
              <h4 className="text-sm font-bold text-white font-serif">
                Predictive Surge Mitigation Protocol
              </h4>
            </div>
            <p className="text-xs text-slate-400 max-w-xl">
              Model recommends activating Ward 4B for 6 additional step-down ICU beds to relieve emergency intake pressure.
            </p>
          </div>
          <button
            onClick={onReviewRecommendation}
            className="px-5 py-2.5 rounded-xl bg-[#E88F89] hover:bg-[#F2A39F] text-slate-950 font-bold text-xs transition-all shadow-md shadow-[#E88F89]/20 shrink-0 active:scale-95"
          >
            Review Surge Model
          </button>
        </div>

        {/* Daily Changes audit trigger */}
        <div className="bg-[#13251B] rounded-2xl p-6 border border-[#234230] shadow-xl flex items-center justify-between">
          <div className="space-y-1">
            <h4 className="text-sm font-bold text-white font-serif">Since Yesterday</h4>
            <p className="text-xs text-slate-400">ICU +8% · Wait +12m · Beds -6</p>
          </div>
          <button
            onClick={() => setDailyChangesModalOpen(true)}
            className="px-3 py-2 rounded-xl bg-[#1C3326] hover:bg-[#234230] text-[#E88F89] text-xs font-semibold border border-[#2C4838] transition-all"
          >
            Audit Changes
          </button>
        </div>
      </div>

      {/* "Daily Changes" Modal */}
      {dailyChangesModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm">
          <div className="bg-[#13251B] rounded-2xl border border-[#2C4838] shadow-2xl max-w-lg w-full p-6 space-y-4 text-slate-100">
            <div className="flex items-center justify-between border-b border-[#1E3B2A] pb-3">
              <div>
                <span className="text-[10px] font-mono uppercase tracking-widest text-[#E88F89]">
                  24-Hour Telemetry Audit
                </span>
                <h3 className="text-lg font-serif font-bold text-white">Daily Operational Changes</h3>
              </div>
              <button
                onClick={() => setDailyChangesModalOpen(false)}
                className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-white/5"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3">
              {DAILY_CHANGES.map((item, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-[#183124] border border-[#234230] flex items-center justify-between">
                  <div>
                    <p className="text-xs font-bold text-white">{item.label}</p>
                    <p className="text-[11px] text-slate-400 mt-0.5">{item.detail}</p>
                  </div>
                  <div className={`px-2.5 py-1 rounded-lg text-xs font-mono font-bold ${
                    item.isConcerning ? 'bg-rose-950/80 text-rose-300 border border-rose-800' : 'bg-emerald-950/80 text-emerald-300 border border-emerald-800'
                  }`}>
                    {item.change}
                  </div>
                </div>
              ))}
            </div>

            <div className="flex justify-end pt-2 border-t border-[#1E3B2A]">
              <button
                onClick={() => setDailyChangesModalOpen(false)}
                className="px-4 py-2 rounded-xl text-xs font-semibold bg-[#1C3326] hover:bg-[#234230] text-slate-300"
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
